### ISSUE TITLE
Failed to decrypt?

### ISSUE THREAD

**Issue by HAPSagan** [weetmuts/wmbusmeters#700] opened 2022-11-25 11:07 UTC
I have tried to decrypt using wmbusmeters.org/analyze but failed. I know that the key is the right one.

https://wmbusmeters.org/analyze/3f442d2c7934347134048d2088a5cc33228ead79eB470f0f048c01005d810200752a010052850100d8670300B21B2c0e50000000200000004900000000000000:auto:E953179E876CFE2D1C2139D366DFF4E2

**Comment by kroimon** [comment] 2022-11-25 14:25
Duplicate of #696.

**Comment by weetmuts** [comment] 2022-12-05 22:38
The telegram is already decrypted. You can see all the zeroes at the end. However it is compressed.
Please collect longer telegrams that will tell wmbusmeters how to decode this telegram.

**Comment by BIBOLV** [comment] 2023-01-03 21:02
Closing as a duplicate of https://github.com/weetmuts/wmbusmeters/issues/696

**Closed by BIBOLV** 2023-01-03 21:02 UTC
